### PR TITLE
LoyaltyCardEditActivity: fix wrong balance parse after locale changes

### LINKED ISSUE #1379: Changing language in card option view changes balance
1. Go to a card edit's options tab
2. Set a balance to for example 5€
3. Switch to the system language settings in Android and change locale (for example US to NL)
4. Switch back to Catima

The value should still be 5€ but is now 500€

### PR DESCRIPTION
**Pull request by obfusk**
Fixes #1379.

The `onResuming`/`onRestoring` checks are needed to make sure the balance doesn't get parsed/changed before it's set to the correct value.

### CODE REVIEW

File: app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java [hunk 1]
```diff
@@ -932,7 +935,16 @@ public void onResume() {
...
+        // Set the balance directly in case the locale (and thus the decimal separator) changed,
+        // since that may cause parseBalance() to return wrong values
+        BigDecimal balance = tempLoyaltyCard.balance == null ? new BigDecimal("0") : tempLoyaltyCard.balance;
+        tempLoyaltyCard = updateTempState(tempLoyaltyCard, LoyaltyCardField.balance, balance);
+        balanceField.setText(Utils.formatBalanceWithoutCurrencySymbol(tempLoyaltyCard.balance, tempLoyaltyCard.balanceType));
+        validBalance = true;
+        Log.d(TAG, "Setting balance (in case locale changed) to " + balance);
+
         onResuming = false;
+        onRestoring = false;
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:947]: I get what you were going for, but I know myself and if it says "Do X in case of Y" my brain tends to interpret it as an `if (Y) { X() }`. So I think using other phrasing would help me in the future. A suggestion:

```suggestion
        // Set the balance
        // We do this before finishing `onResuming` and `onRestoring` to prevent `formatBalanceCurrencyField` from triggering a reformat (which can cause issues when switching locale)
        BigDecimal balance = tempLoyaltyCard.balance == null ? new BigDecimal("0") : tempLoyaltyCard.balance;
        tempLoyaltyCard = updateTempState(tempLoyaltyCard, LoyaltyCardField.balance, balance);
        balanceField.setText(Utils.formatBalanceWithoutCurrencySymbol(tempLoyaltyCard.balance, tempLoyaltyCard.balanceType));
        validBalance = true;
        Log.d(TAG, "Setting balance to " + balance);

        onResuming = false;
        onRestoring = false;
```

Comment (TheLastProject) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:947]: Do we maybe want to pull line 832 (`formatBalanceCurrencyField(tempLoyaltyCard.balanceType);` down here to put all balance-related operations together?

Comment (obfusk) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:947]: I didn't think that was needed since the `formatBalanceCurrencyField` now no longer affects the balance field during this function. But I can move it if you prefer.

Comment (obfusk) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:947]: I'll update the comment too.

Comment (TheLastProject) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:947]: Yeah I know it's not necessary, but I find the code easier to follow is the balance-related operations are grouped, is all.

Comment (obfusk) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java]: If I move `formatBalanceCurrencyField(tempLoyaltyCard.balanceType)` down, the `startWithoutParametersViewBack` test fails. So I moved everything up.

Comment (obfusk) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java]: That makes more sense anyway. Should probably not have put it below the `initDone`, but it worked fine before I moved that one too.
