### PR TITLE
LoyaltyCardEditActivity: fix state loss on rotation for dates

### LINKED ISSUE #1432: Valid from / Expiry date field reset on configuration change in LoyaltyCardEditActivity
Noticed this while reviewing #1431, it happened before the MR already so not related:

1. Edit a card
2. Change the valid from field
3. Rotate the screen
4. Notice the valid from field is reset
(Same happens with the expiry date field)

I guess it is not in the bundle to restore the configuration between rotations or not updated correctly on change, will have to look.

### PR DESCRIPTION
**Pull request by obfusk**
Fixes #1432 by making sure `updateTempState()` is always called IFF `setTag()` is (unless the tag is set using the temp state).

### CODE REVIEW

File: app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java [hunk 1]
```diff
@@ -405,7 +405,9 @@ public void noDataLossOnResumeOrRotate() {
             storeField.setText("correct store");
             noteField.setText("correct note");
             LoyaltyCardEditActivity.formatDateField(context, validFromField, validFromDate);
+            activity.updateTempState(LoyaltyCardField.validFrom, validFromDate);
             LoyaltyCardEditActivity.formatDateField(context, expiryField, expiryDate);
+            activity.updateTempState(LoyaltyCardField.expiry, expiryDate);
```
Comment (TheLastProject) [inline app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java:410]: I'm not a huge fan of copying these specific calls into tests as it makes the tests untrustworthy (they will pass even when the code is changed to break it again). But I will still merge it if this fixes it because the test is not **more untrustworthy** than before at least (still have to test your patch)

Comment (obfusk) [reply app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java:410]: Yeah, I wasn't happy with that either. But it was needed. I can wrap both calls in a new function instead if you prefer.

Comment (obfusk) [reply app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java:410]: I tested with Android 13 (emulator). But more testing is always a good idea.

Comment (obfusk) [reply app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java:410]: Not sure the test should be calling `formatDateField()` directly either. But I didn't want to mess with things more than necessary for this PR. Happy to follow up with some cleanup if you want.

Comment (TheLastProject) [reply app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java:410]: > Not sure the test should be calling formatDateField() directly either. But I didn't want to mess with things more than necessary for this PR. Happy to follow up with some cleanup if you want.

Yeah, that's what I meant with the test is not "more untrustworthy" because it already was untrustworthy.

A follow-up at some point would be great, but out of scope. Just wanted to make sure we agreed here :)

Comment (obfusk) [reply app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java:410]: Yeah, definitely :)
