### PR TITLE
Fixes to currency parsing

### LINKED ISSUE #953: Can't save card in Arabic
It looks like the balance sanity checking code is broken and doesn't know how to deal with arabic 0.

Screenshot_20220724-002326_Trebuchet

### PR DESCRIPTION
**Pull request by TheLastProject**
Fixes #953

### CODE REVIEW

File: app/src/test/java/protect/card_locker/UtilsTest.java [hunk 1]
```diff
@@ -14,53 +15,53 @@
 @Config(sdk = 23)
 public class UtilsTest {
     @Test
-    public void parseBalances() {
-        assertEquals("1", Utils.parseCurrency("1", false).toPlainString());
-
-        assertEquals("1", Utils.parseCurrency("1", true).toPlainString());
-        assertEquals("1.00", Utils.parseCurrency("1.00", true).toPlainString());
-        assertEquals("1.00", Utils.parseCurrency("1,00", true).toPlainString());
```
Comment (Altonss) [inline app/src/test/java/protect/card_locker/UtilsTest.java:22]: This line seem to fail in the tests

Comment (Altonss) [reply app/src/test/java/protect/card_locker/UtilsTest.java:22]: The comma probably needs to be replaced with a dot in the parser

Comment (TheLastProject) [reply app/src/test/java/protect/card_locker/UtilsTest.java:22]: I actually think the tests are just wrong in the first place. I tried to be overly clever.

But right now parsing anything with decimals goes wrong.

It's honestly scary to touch this code, but #953 is a pretty awful bug :(

Comment (TheLastProject) [reply app/src/test/java/protect/card_locker/UtilsTest.java:22]: Specifically, I tried to write it so that using . instead of , or the other way around doesn't really matter. But honestly that was probably not very useful to code and I should've just stuck to whatever the device or selected locale does.

Comment (TheLastProject) [reply app/src/test/java/protect/card_locker/UtilsTest.java:22]: Okay, it now seems to work. I think writing tests for core Android features is kinda silly anyway so I'll do more manual testing and then probably delete the tests (because then I'd just be testing Android's .parse)
