### PR TITLE
Fix balance unexpected rounding and app crashing issue

### LINKED ISSUE #1506: protect.card_locker.Utils.parseBalance: java.lang.NumberFormatException
Found in Google Play Console

Catima 2.25.3 on samsung a3core (Galaxy A03 Core) running Android 11 (SDK 30)

Not sure how they managed to set that input string but okay.

```
Exception java.lang.NumberFormatException: For input string: "Infinity"
  at java.lang.Long.parseLong (Long.java:594)
  at java.lang.Long.parseLong (Long.java:636)
  at java.math.BigDecimal.<init> (BigDecimal.java:344)
  at java.math.BigDecimal.<init> (BigDecimal.java:425)
  at protect.card_locker.Utils.parseBalance (Utils.java:309)
  at protect.card_locker.LoyaltyCardEditActivity$3.onTextChanged (LoyaltyCardEditActivity.java:410)
  at android.widget.TextView.sendOnTextChanged (TextView.java:10769)
  at android.widget.TextView.handleTextChanged (TextView.java:10876)
  at android.widget.TextView$ChangeWatcher.onTextChanged (TextView.java:14328)
  at android.text.SpannableStringBuilder.sendTextChanged (SpannableStringBuilder.java:1267)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:576)
  at androidx.emoji2.text.SpannableBuilder.replace (SpannableBuilder.java:315)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:507)
  at androidx.emoji2.text.SpannableBuilder.replace (SpannableBuilder.java:305)
  at androidx.emoji2.text.SpannableBuilder.replace (SpannableBuilder.java:49)
  at android.view.inputmethod.BaseInputConnection.replaceText (BaseInputConnection.java:861)
  at android.view.inputmethod.BaseInputConnection.commitText (BaseInputConnection.java:197)
  at com.android.internal.widget.EditableInputConnection.commitText (EditableInputConnection.java:177)
  at android.view.inputmethod.InputConnectionWrapper.commitText (InputConnectionWrapper.java:169)
  at com.android.internal.view.IInputConnectionWrapper.executeMessage (IInputConnectionWrapper.java:345)
  at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage (IInputConnectionWrapper.java:93)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7815)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:593)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1094)
```

### PR DESCRIPTION
**Pull request by simosathan9**
Fixes #1506 

This commit resolves two issues affecting the balance field:

1. Fixed a bug causing the app to crash when entering excessively large values into the balance field.
2. Addressed an unexpected rounding behavior where certain values were rounded up. For instance, inputting '999999999999999' would erroneously round up to '1000000000000000'.

In the parseBalance method, I implemented a check to verify if the NumberFormat instance is an instance of DecimalFormat. If it is, I enabled the parsing of BigDecimal values by setting setParseBigDecimal(true). This ensures accurate handling of large numeric values and prevents unexpected rounding behavior.

### CODE REVIEW

File: app/src/main/java/protect/card_locker/Utils.java [hunk 1]
```diff
@@ -422,16 +423,18 @@ static public String formatBalanceWithoutCurrencySymbol(BigDecimal value, Curren
...
             numberFormat.setMaximumFractionDigits(0);
         } else {
             numberFormat.setMinimumFractionDigits(currency.getDefaultFractionDigits());
             numberFormat.setMaximumFractionDigits(currency.getDefaultFractionDigits());
         }
 
-        Log.d(TAG, numberFormat.parse(value).toString());
-
-        return new BigDecimal(numberFormat.parse(value).toString());
+        return (BigDecimal) numberFormat.parse(value);
```
Comment (electroCutie) [inline app/src/main/java/protect/card_locker/Utils.java:437]: Rarely this could fail since `NumberFormat.getInstance()` is not guaranteed to return an instance of `DecimalFormat`
We could add a function to handle those cases
```
private static final double LargestPreciseDouble = (double) (1l << 53);
static{
    assert (LargestPreciseDouble + 1.0) == LargestPreciseDouble;
    assert (LargestPreciseDouble - 1.0) != LargestPreciseDouble;
}

private static BigDecimal fromParsed(Number parsed){
    if(parsed instanceof BigDecimal)
      return (BigDecimal) parsed;

    final double d = parsed.doubleValue();
    if(d >= LargestPreciseDouble)
      return new BigDecimal(parsed.longValue());
    return new BigDecimal(d);
}
```
    
and then make this line `return fromParsed(numberFormat.parse(value));`

Comment (simosathan9) [reply app/src/main/java/protect/card_locker/Utils.java:437]: First of all thank you for your feedback !

I tested the code that you suggested to use and I observed that when I add for example the number 9999999999999999999 (19 times the number 9 or more) it is converted to 9,223,372,036,854,775,807 which is the value of the `LargestPreciseDouble` variable. 
You mention with the assertion that  `(LargestPreciseDouble + 1.0) == LargestPreciseDouble` must hold. 
I believe that when you assign a value to the variable d in the line `final double d = parsed.doubleValue();` if `parsed` is greater than `LargestPreciseDouble` , then d is assigned with the value of `LargestPreciseDouble` and that's why this behavior is observed. Do you have any suggestions how we could overcome this ?

Comment (TheLastProject) [reply app/src/main/java/protect/card_locker/Utils.java:437]: Hmm, interesting. I tried @electroCutie's patch and can't reproduce your issue (with 20 taps of 9):

[Screen_recording_20240421_132234.webm](https://github.com/CatimaLoyalty/Android/assets/1885159/85f795ea-6c20-4e34-8c74-33ca4574fe05)

Are you testing it the same way as me? Entering numbers from the keyboard and then tapping away? Or are you doing something else?

Comment (simosathan9) [reply app/src/main/java/protect/card_locker/Utils.java:437]: Well I do the same steps and this is what happens. 

[Uploading Catima_Loyalty_20240421_213602.webm…]()

Comment (simosathan9) [reply app/src/main/java/protect/card_locker/Utils.java:437]: Well I do the same steps but this is what happens 
[Catima_Loyalty_20240421_213602.webm](https://github.com/CatimaLoyalty/Android/assets/115111582/161ce7b8-057e-4685-9252-3c88838f7bae)

Comment (TheLastProject) [reply app/src/main/java/protect/card_locker/Utils.java:437]: Hmm, interesting. I can't reproduce it. Could you please push the code with @electroCutie's change so we can be sure we're talking about the same code?

Comment (simosathan9) [reply app/src/main/java/protect/card_locker/Utils.java]: I pushed the code with @electroCutie's changes but then noticed that mistakenly I had erased these lines 
`if (numberFormat instanceof DecimalFormat) {`
            `(DecimalFormat)` `numberFormat).setParseBigDecimal(true);`
  `}`

By adding them it worked as expected for me as well !!

**Comment by TheLastProject** [comment]
Sorry for taking so long to get back to you. After some very thorough testing I seem to be unable to break this code so I think this is indeed working great. Thank you @simosathan9 and @electroCutie!

(I did notice another bug, #1856, but I can confirm this already happens in the stable release so that's not caused by your code)
