### PR TITLE
Fix crash on configuration changes in DatePickerFragment

### LINKED ISSUE #1201: Crash when returning if date picker was left open
How to reproduce:
1. Create/Edit a card
2. Go to the Options tab
3. Click "Choose expiry date" under "Expiry date"
4. Switch to another app
5. Switch back to Catima

Device:
Fairphone 3, LineageOS for microG 19.1 (Android 12.1)

Crash:
```
FATAL EXCEPTION: main
Process: me.hackerchick.catima, PID: 29237
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.hackerchick.catima/protect.card_locker.LoyaltyCardEditActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment protect.card_locker.LoyaltyCardEditActivity$DatePickerFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment protect.card_locker.LoyaltyCardEditActivity$DatePickerFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at protect.card_locker.CatimaAppCompatActivity.onCreate(CatimaAppCompatActivity.java:24)
	at protect.card_locker.LoyaltyCardEditActivity.onCreate(LoyaltyCardEditActivity.java:308)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	... 12 more
Caused by: java.lang.NoSuchMethodException: protect.card_locker.LoyaltyCardEditActivity$DatePickerFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getConstructor(Class.java:1759)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 27 more
```

### PR DESCRIPTION
**Pull request by unbiaseduser**
Fixes #1201. When you tab in and out of other apps or rotate your screen, the `DatePickerFragment` won't cause crashes anymore.
Let me explain how the fix works:
- `Fragment`s must have a public, no arguments constructor. Any data you want to pass to them must be put in a `Bundle` for Android to be able to persist it across configuration changes (like the situations above).
- Communication between fragments or between an activity and a fragment is performed with `FragmentManager.setFragmentResultListener()` on the activity/fragment that receives the callback and `FragmentManager.setFragmentResult()` on the one that sends the callback. The callback data must fit in a `Bundle`.

In the original code, the date picker directly sets the target text field. Here, the code for setting the text field is put in a callback received by the host activity, and the date picker fragment's only responsibility is receiving input data (the `Date` objects) and sending output data (the picked `Date`). To know which text field to set, I pass in an "identifier" (which conveniently is the `LoyaltyCardField` enum that's already used in the "display date picker" method, so I don't have to create a new enum or something.)

### CODE REVIEW

File: app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java [hunk 1]
```diff
@@ -967,10 +983,9 @@ public void onTextChanged(CharSequence s, int start, int before, int count) {
...
                         dateField.setText(lastValue);
                     }
-                    DialogFragment datePickerFragment = new DatePickerFragment(
-                            LoyaltyCardEditActivity.this,
-                            dateField,
-                            // if the expiry date is being set, set date picker's minDate to the 'valid from' date
+                    DialogFragment datePickerFragment = DatePickerFragment.newInstance(
+                            loyaltyCardField,
+                            (Date) dateField.getTag(),
                             loyaltyCardField == LoyaltyCardField.expiry ? (Date) validFromField.getTag() : null,
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:989]: Looks like you accidentally removed one comment too much

```suggestion
                            // if the expiry date is being set, set date picker's minDate to the 'valid from' date
                            loyaltyCardField == LoyaltyCardField.expiry ? (Date) validFromField.getTag() : null,
```

File: app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java [hunk 2]
```diff
@@ -1336,27 +1351,54 @@ public void onDialogDismissed(int dialogId) {
...
+                    (requestKey, result) -> listener.onDatePicked(
+                            (LoyaltyCardField) Objects.requireNonNull(result.getSerializable(TEXT_FIELD_TO_EDIT_ARGUMENT_KEY)),
+                            (Date) Objects.requireNonNull(result.getSerializable(NEWLY_PICKED_DATE_ARGUMENT_KEY))));
+        }
+
+        LoyaltyCardField textFieldEdit;
+        @Nullable
+        Date minDate;
+        @Nullable
+        Date maxDate;
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:1389]: Nitpick: I would've personally preferred these statements below the `private static final String` and above the `newInstance`. So, at line 1360 at the time of writing :)

**Review by TheLastProject — CHANGES_REQUESTED** [review]
This looks great and works well. Thanks for the fix and the detailed explanation! I just have a few nitpicks, nothing big :)

File: app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java [hunk 3]
```diff
@@ -1336,27 +1352,54 @@ public void onDialogDismissed(int dialogId) {
...
+            args.putSerializable(TEXT_FIELD_TO_EDIT_ARGUMENT_KEY, textField);
+            args.putSerializable(CURRENT_DATE_ARGUMENT_KEY, currentDate);
+            args.putSerializable(MIN_DATE_ARGUMENT_KEY, minDate);
+            args.putSerializable(MAX_DATE_ARGUMENT_KEY, maxDate);
+            DatePickerFragment fragment = new DatePickerFragment();
+            fragment.setArguments(args);
+            return fragment;
+        }
+
+        public interface OnDatePickListener {
```
Comment (obfusk) [inline app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:1379]: I would suggest having nested classes/interfaces at the top of their containing class, not in between its methods.

File: app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java [hunk 4]
```diff
@@ -1336,27 +1352,54 @@ public void onDialogDismissed(int dialogId) {
     public static class DatePickerFragment extends DialogFragment
             implements DatePickerDialog.OnDateSetListener {
 
-        final Context context;
-        final EditText textFieldEdit;
+        private static final String TEXT_FIELD_TO_EDIT_ARGUMENT_KEY = "text_field_to_edit";
+        private static final String CURRENT_DATE_ARGUMENT_KEY = "current_date";
+        private static final String MIN_DATE_ARGUMENT_KEY = "min_date";
+        private static final String MAX_DATE_ARGUMENT_KEY = "max_date";
+        private static final String PICK_DATE_REQUEST_KEY = "pick_date_request_key";
```
Comment (obfusk) [inline app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:1359]: Any reason the value ends with "_key" unlike the others?

Comment (unbiaseduser) [reply app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java:1359]: Nothing, really. I'll just remove it.

**Comment by TheLastProject** [comment]
Thanks!

**Comment by obfusk** [comment]
Thanks for the fix and the explanation. Learned something new :)
