### PR TITLE
Fix a crash when there's no web browser installed

### LINKED ISSUE #984: Android 12: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://play.google.com/... }
Caught by Google Play Pre-launch report. Probably a device without browser. This should be very easy to "fix" by instead showing a toast telling the user the URL couldn't be opened:

```
FATAL EXCEPTION: Thread-2
Process: me.hackerchick.catima, PID: 9955
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://play.google.com/... }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
	at android.app.Activity.startActivityForResult(Activity.java:5404)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5362)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5748)
	at android.app.Activity.startActivity(Activity.java:5701)
	at protect.card_locker.AboutActivity.onClick(AboutActivity.java:169)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

https://user-images.githubusercontent.com/1885159/184538215-7e512959-01d7-460c-b9d4-669cc107e047.mp4

### PR DESCRIPTION
**Pull request by vanogrid**
Fixes #984

I tested it by running emulators with different API versions and disabling the default web browser. Tested on Android 8.1, 12 and 13.

Signed-off-by: Alexander Ivanov <vanogrid@gmail.com>

### CODE REVIEW

File: app/src/main/java/protect/card_locker/AboutActivity.java [hunk 1]
```diff
@@ -166,7 +167,11 @@ public void onClick(View view) {
 
         Intent intent = new Intent(Intent.ACTION_VIEW);
         intent.setData(Uri.parse(url));
-        startActivity(intent);
+        if (intent.resolveActivity(getPackageManager()) != null) {
```
Comment (TheLastProject) [inline app/src/main/java/protect/card_locker/AboutActivity.java:170]: Please instead catch the exception when startActivity failed. API level 30 added extra restrictions to resolveActivity which may make it return null even if a browser is available: https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30

There's an example in https://github.com/CatimaLoyalty/Android/blob/0189f13ee652bd154f1171981880d2bac4f63e9d/app/src/main/java/protect/card_locker/ImportExportActivity.java#L148-L153.

**Review by TheLastProject — CHANGES_REQUESTED** [review]

File: app/src/main/java/protect/card_locker/AboutActivity.java (hunk 1 above)
Comment (vanogrid) [reply app/src/main/java/protect/card_locker/AboutActivity.java]: Oops, I wasn't aware of the new restrictions. I updated the PR, please have another look.

**Comment by TheLastProject** [comment]
Looks good, thanks!

bors r+
